controller_list:
  - name: fake_zeus_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
  - name: fake_hand_controller
    joints:
      - joint_5
initial:  # Define initial robot poses.
  - group: zeus_arm
    pose: Candle
  - group: hand
    pose: Home