language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen

# command to run tests
script:
  - pytest
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
