teleop:
  walk:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    deadman_buttons: [4,5]
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 0.5
        offset: -0.03
      -
        axis: 0
        target: angular.z
        scale: 0.5
      -
        axis: 2
        target: linear.y
        scale: 0.3
      -
        button: 2
        target: linear.z
        scale: 3.0

