nb_sensors: 3
sensor_1:
  name: realsense
  sensor_id: realsense
  topic: /realsense/color/image_raw
  max_freq: 20
  min_freq: 0.5

sensor_2:
  name: gps
  sensor_id: gps
  topic: /navsat/fix
  max_freq: 60
  min_freq: 20

sensor_3:
  name: imu
  sensor_id: imu
  topic: /imu/data
  max_freq: 60
  min_freq: 20


